# Copyright 2025 Lunch Pail Labs, LLC
# Licensed under the Apache License, Version 2.0

"""
Extract Insights Step

This step extracts insights and assesses competencies from the interview.
"""

import logging
from typing import Any, Dict, List, cast

from flow.steps.interview.base import InterviewStep

logger = logging.getLogger(__name__)


class ExtractInsightsStep(InterviewStep):
    """
    Extract insights and assess competencies.

    **Simple Explanation:**
    This step analyzes the candidate's answers to figure out:
    - How well they answered each question
    - What competencies they demonstrated
    - Overall strengths and weaknesses
    It's like having an expert reviewer analyze the interview.
    """

    def __init__(self):
        super().__init__(
            name="extract_insights",
            description="Extract insights and assess candidate competencies",
        )

    async def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute insight extraction.

        Args:
            state: Current workflow state containing qa_pairs and interview_config

        Returns:
            Updated state with insights
        """
        # Validate required state
        if not self.validate_state(state, ["qa_pairs"]):
            return self.set_error(state, "Missing required state: qa_pairs")

        qa_pairs = state.get("qa_pairs", [])
        interview_config = state.get("interview_config", {})
        competencies = interview_config.get("competencies", [])

        logger.info("🧠 Extracting insights and assessing competencies")

        # TODO: Replace with actual AI-based analysis
        # In a real implementation, this would use an AI model to analyze
        # the answers and provide detailed assessments. For now, we'll create
        # a basic structure.

        insights: Dict[str, Any] = {
            "overall_score": 0.0,  # Would be calculated based on answers
            "competency_scores": {comp: 0.0 for comp in competencies},
            "strengths": [],
            "weaknesses": [],
            "question_assessments": [],
        }

        # Assess each Q&A pair
        for i, qa in enumerate(qa_pairs):
            assessment = {
                "question_id": qa.get("question_id"),
                "question": qa.get("question"),
                "answer_length": len(qa.get("answer", "")),
                "score": 0.0,  # Would be calculated by AI
                "notes": "Assessment would be generated by AI analysis",
            }
            cast(List[Dict[str, Any]], insights["question_assessments"]).append(
                assessment
            )

        state["insights"] = insights
        state = self.update_status(state, "insights_extracted")

        logger.info(f"✅ Extracted insights for {len(qa_pairs)} questions")

        return state
