# fly.toml app configuration file generated for pailkit-api on 2024-12-20T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pailkit-api"
primary_region = "iad"

[build]
  # We'll use a Dockerfile for building
  # If you prefer buildpacks, you can change this to use the Python buildpack

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # HTTP health checks removed - all endpoints require authentication
  # Fly.io will still monitor machine health at the infrastructure level
