# Ruff configuration for PailKit API
line-length = 100

[lint]
# Enable unused imports and other quality checks
select = [
    "F",      # Pyflakes (includes unused imports)
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "I",      # isort (import sorting)
    "B",      # flake8-bugbear (common bugs)
    "C4",     # flake8-comprehensions (complexity)
    "UP",     # pyupgrade (modern Python features)
]

# Ignore specific rules if needed
ignore = []

# Exclude common directories
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
]
